version: '3.1'
services:
    service:
        build: 
            context: sample-service/.
        image: "sample_service:1.0.${BUILD_NUMBER}"
        restart: always
        container_name: 'sample-service'
        ports:
            - "8181:8181"
        environment:
            - NODE_ENV=development
        links: 
            - mongo:mongo
    mongo:
        build: 
            context: db/.
        image: "sample_db:1.0.${BUILD_NUMBER}"
        container_name: 'sample-db'
        restart: always
        ports:
            - "25017:27017"
        volumes:
            - /data/sample:/data/db:rw
        command: mongod --auth